# Generated by Django 2.0.1 on 2018-09-25 14:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20180829_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'The value should be more than %(limit_value)s.')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'The value should be more than %(limit_value)s.')]),
        ),
    ]
