# Generated by Django 2.0.1 on 2018-09-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180925_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Creator',
            new_name='creator',
        ),
    ]
